### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by ghost** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#1]
播放模式为单曲循环时 结束一次播放后再次播放不会更新信息
![](https://i.imgur.com/04zHq8R.png)

**Comment by Kxnrl** [comment]
已在2.0中修复
https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/commit/83b9c0e03a9900e9cc9428e292067cbc1a0196eb
