### ISSUE TITLE
网易云2.9.4 好像G了

### ISSUE THREAD

**Issue by Jayjjjjj** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#10]
![image](https://user-images.githubusercontent.com/25612083/134291829-4c8c1fee-2c88-46a8-8dad-957083bcbeb2.png)
Discord Version:
Stable 98341 (b069aec) Host 1.0.9002 Windows 10 64-Bit (10.0.19042)
Netease Music Version:
![image](https://user-images.githubusercontent.com/25612083/134291918-73bf985f-4cfb-402b-adfb-46559a12049b.png)

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/commit/0c0c6f2ce31e985d3f6f597b6ff4fccb75a8a0d7
