### ISSUE TITLE
QQ音乐：暂停音乐后状态不消失

### ISSUE THREAD

**Issue by npackr** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#12]

**Comment by npackr** [comment]
> QQ音乐暂时无法解决该问题，也无法显示剩余时间。因为实现方式与网抑云和spotify差异很大，还没有找到可行的替代方案
我想想如果大佬利用投放功能来获取这些数据可不可以，每次想使用就用Qplay链接到一个虚伪设备，这个虚伪设备是你的软件创新和控制的，这样子的话应该可以获取很多信息，还可以控制播放进度等等。同样的方式，其他音乐平台应该都支持这个投放功能。但是，我只是这么想而已，因为对于桌面程序变成来说我不太了解。不知道大佬觉得这个我说的这个方向可不可以实现 
🥲

**Comment by Kxnrl** [comment]
2.3版本已经有一些眉目了

**Comment by npackr** [comment]
> 2.3版本已经有一些眉目了
期待~ 😚

**Comment by Kxnrl** [comment]
QQ音乐实时状态需要 2.45+

![image](https://github.com/user-attachments/assets/50b5be06-92b9-40c3-84ea-aee84f7d24c8)
