### ISSUE TITLE
在打开VS Code以后没有自动清除状态

### ISSUE THREAD

**Issue by EagleZhen** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#13]
在打开VS Code以后没有自动清除状态
要暂停音乐，或者关掉ncm-rpc以后才显示回VS Code的rpc

我看到windows.txt里面有Code.exe，所以我猜正常来说应该是VS Code优先显示吧？

**Comment by Kxnrl** [comment]
release build还是你自己的build

**Comment by EagleZhen** [comment]
2.2-Release build

**Comment by EagleZhen** [comment]
补充一下，一开始我用的是预设的windows.txt
```
// Visual Studio
VisualStudioAppManagement
devenv.exe

// Visual Studio Code
Code.exe

// SourceEngine Game
Valve001

// UnrealEngine Game
UnrealWindow

// Unity3D Game
UnityWndClass

// Shit Game
Rainbow Six
```
这样在开启vs code的时候并不会清楚状态
但我刚刚试了一下，将其它所有东西都删掉，只剩下
```
// Visual Studio Code
Code.exe
```
这样反而就正常运作了

**Comment by Kxnrl** [comment]
> 
删掉``VisualStudioAppManagement``这一行看看呢

**Comment by EagleZhen** [comment]
> 删掉`VisualStudioAppManagement`这一行看看呢

经过测试是`devenv.exe`这一行出了问题，只删掉这一行就能正常显示VS Code了
