### ISSUE TITLE
程序初始化时 Failed to get offset

### ISSUE THREAD

**Issue by remiliacn** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#14]
### 运行环境
Windows 11 Professional 10.0.22000 Build 22000

### 复现方式
双击启动程序，弹出信息框：
Title: Failed to get offset 
Content: Response status code does not indicate success: 504(Gateway Time-out).

**Comment by npackr** [comment]
同样问题

Edition	Windows 10 Pro
Version	21H2
Installed on	‎02/‎05/‎2021
OS build	19044.1348
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by EagleZhen** [comment]
一样问题

Windows 10
网易云版本：2.9.5 Build (199424)

**Comment by Kxnrl** [comment]
Fixed
