### ISSUE TITLE
RPC失效

### ISSUE THREAD

**Issue by EagleZhen** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#16]
最近好像突然间失效了，在Discord上不会显示RPC，重启过网易云、DiscordRPC、Discord也没有效果

Discord版本 Stable 11867(6948c1e)
DiscordRPC版本 2.2.0.0
网易云版本 2.9.7(Build:199711) (Patch: 1:86d53a4)

**Comment by Kxnrl** [comment]
还没有更新2.9.7的offset, 最近过年没什么时间弄这个.
如果你有offset可以提交PR

**Comment by EagleZhen** [comment]
想请教下offset其实指的是啥？我如果有能力的话或许可以试试

**Comment by idkwhat2say** [comment]
^^

**Comment by Kxnrl** [comment]
Updated
