### ISSUE TITLE
Failed to get offsets

### ISSUE THREAD

**Issue by coolsna** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#17]
网易云2.9.7和网易云2.9.8（最新版）运行时显示 响应状态代码不指示成功：502（Bad Gateway）

**Comment by Kxnrl** [comment]
CDN挂了, 现在好了

**Comment by Kxnrl** [comment]
> 2.9.8版本 似乎还没修复好的样子，在discord上还是显示不了

按照网易的尿性, 2.9.8可能有很多个版本, 所以你需要build id来确认, 我今天在我pc上的2.9.8测试仍然是可以使用的. 所以你需要提供一下``build id``

**Comment by idkwhat2say** [comment]
> 

199759
