### ISSUE TITLE
The hyphen in the names causes a display bug.

### ISSUE THREAD

**Issue by EagleZhen** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#19]
![image](https://user-images.githubusercontent.com/31062364/161169344-627b3a8f-30fb-4498-a545-07b215378d74.png)
![image](https://user-images.githubusercontent.com/31062364/161169379-9a0fa439-d93b-453d-9abf-cea075950d9f.png)
What it should display is "安室奈美恵" on the artist field,  "Hope - （from BEST AL [Finally])" on the title field.

**Comment by Kxnrl** [comment]
can you post the sound file here? or send to kyle@kxnrl.com

**Comment by z3l1nt** [comment]
兄弟能出个教程吗，coding小白尽力了但是还是没玩懂怎么让dc显示网易云音乐动态。。。

**Comment by Kxnrl** [comment]
> 兄弟能出个教程吗，coding小白尽力了但是还是没玩懂怎么让dc显示网易云音乐动态。。。

你的问题与当前Issue无关, 如果需要提问请开新的Issue

**Comment by z3l1nt** [comment]
> 

没问题

**Comment by EagleZhen** [comment]
Sorry for the late reply. Here is the link to the file.
[安室奈美恵 - Hope - （from BEST AL [Finally]).mp3](https://drive.google.com/file/d/10dA0JSadmmr-MnyARB9TM7SmlPhrWAGQ/view?usp=sharing)

**Comment by Kxnrl** [comment]
这个是因为你文件名本身就被网易云识别错误, 按照网易云写法, 他是会在文件的MP3TAG中写入实际数据, 并不是简单的读取文件名, 所以造成改问题的原因是MP3TAG错误
