### ISSUE TITLE
小白求教程！！！谢谢大佬！

### ISSUE THREAD

**Issue by z3l1nt** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#20]
![image](https://user-images.githubusercontent.com/104236536/164817321-fa1c6d3d-4777-4d87-8a3e-ee1a3984ff43.png)
文件下载好了以后不知道需要从哪里导入进去，有点迷茫
求大佬给个教程
discord：Oranji.#1999

**Comment by Kxnrl** [comment]
从这里 https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/releases/tag/2.2.0

**Comment by z3l1nt** [comment]
大佬我这边下好了已经
![image](https://user-images.githubusercontent.com/104236536/164874171-c51847ce-6f2f-4d46-81cd-1b346171a5f6.png)
![image](https://user-images.githubusercontent.com/104236536/164874177-f8cdacda-c327-4d2d-9869-ef6b8c711073.png)
但是discord并没有相关的选项啥的。。。
![image](https://user-images.githubusercontent.com/104236536/164874218-0e581025-9619-4149-9da0-7312fbcb2a6e.png)
然后我看到您帖子上的留言
![image](https://user-images.githubusercontent.com/104236536/164874257-c24d9a6d-8a5d-4f31-9dd9-780028453c3a.png)
这个关于FindWindow的链接已经打不开了，google了一下也没看到相似的操作说明。
是需要再下载一个discord的Rich Presence才能完美运行吗

**Comment by Kxnrl** [comment]
你网易云的版本和``build id``多少, 启动时有误报错, 还有你可以尝试清空``windows.txt``

**Comment by z3l1nt** [comment]
网易云版本与系统版本如下

![image](https://user-images.githubusercontent.com/104236536/164874570-744e46ab-ec89-4ed3-b0a7-bab19a07276a.png)
![image](https://user-images.githubusercontent.com/104236536/164874594-77ffc89d-07e5-44d6-a922-ff005ad42075.png)

启动时无报错

**Comment by Kxnrl** [comment]
emm 版本太高了. 等更新吧
我还没有收到2.9.9的推送. 我也没法检测这个

**Comment by z3l1nt** [comment]
谢谢大佬

**Comment by Kxnrl** [comment]
updated
