### ISSUE TITLE
"Failed to get offsets" error on startup

### ISSUE THREAD

**Issue by SweetCandy233** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#21]
Screenshot:
![image](https://user-images.githubusercontent.com/68184088/174451591-861459ac-4934-4b0d-9185-4b50a6f498b3.png)

Running on Windows 10 21H2, with Netease CloudMusic Desktop version `2.9.6 (Build: 199543) (Patch:1:4674a53)`

Please let me know if further information is required.

**Comment by Kxnrl** [comment]
still？
