### ISSUE TITLE
新版网易云失效

### ISSUE THREAD

**Issue by EagleZhen** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#22]
网易云版本：2.9.10(Build:200061) (Patch:1:a774a61)

在重启了网易云和NCM-DiscordRpc.exe以后也依然没有显示任何内容

**Comment by Cloud370** [comment]
偏移变了
网易云版本：2.9.10(Build:200061) (Patch:1:a774a61)
当前时间：`cloudmusic.dll+9E4350`
总时长：`cloudmusic.dll+A941D8`

**Comment by Kxnrl** [comment]
当前是考虑使用mem signature + offset来实现. 之前的纯offset方式会导致每次更新都会发生偏移量变化. 预计会再2.2版本使用

**Comment by Cloud370** [comment]
> 

hook太坑了 很多东西拿不到 我直接嵌入JS往外传数据了

**Comment by Kxnrl** [comment]
> 9E4350

![image](https://user-images.githubusercontent.com/3905845/174930965-617c2ed0-01dd-404c-93e9-0f5872a74571.png)

你可以尝试这个

**Comment by Cloud370** [comment]
刚开始我就找的这个，这个似乎是个js变量内存里面，附近还有ID和当前进度时间等等，但是不好找基址
现在看起来好像有hook内存和注入JS以及本地文件三种方案 我都写了兼容

**Comment by Kxnrl** [comment]
> 刚开始我就找的这个，这个似乎是个js变量内存里面，附近还有ID和当前进度时间等等，但是不好找基址 现在看起来好像有hook内存和注入JS以及本地文件三种方案 我都写了兼容

试试pattern scan然后+offset

**Comment by Cloud370** [comment]
> 

扫到很多个 有的不是最新的 找不到一个固定的规律

**Comment by Kxnrl** [comment]
> ``sub_10177260`` 这个func应该不是每次都会发生变化. 我对比了2.9.9和现在的. 是一样的签名

**Comment by Kxnrl** [comment]
``55 8B EC 83 E4 F8 6A FF 68 ? ? ? ? 64 A1 00 00 00 00 50 83 EC 3C A1 ? ? ? ? 33 C4 50 8D 44 24 40 64 A3 00 00 00 00 F2 0F 10 4D 0C`` + ``92``

**Comment by Cloud370** [comment]
谢谢 内存这块 我还是小白 到时候你更新完了我再参考一下

**Comment by EagleZhen** [comment]
新版 2.10.3 好像失效了
