### ISSUE TITLE
网易云更新2.10.5 rpc失效了

### ISSUE THREAD

**Issue by officialrolly** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#23]
![image](https://user-images.githubusercontent.com/53384267/197457993-90e9d4d1-0c43-4884-82c8-34ae11312e8f.png)
没有rpc

**Comment by aliencaocao** [comment]
请问如何自己扫描offset？我有cheat engine

**Comment by aliencaocao** [comment]
扫描到了2.10.6的offset
```
current: 0xA65568
maxlen: 0xB16438
```

**Comment by aliencaocao** [comment]
你好，可以试试我的版本，支持最新版2.10.6，但是不支持歌曲总时长显示
https://github.com/aliencaocao/netease_cloudmusic_discord_rpc

**Comment by Kxnrl** [comment]
最近都比较忙, 暂时还没时间研究这个, 抱歉了哈
