### ISSUE TITLE
新版网易云失效

### ISSUE THREAD

**Issue by EagleZhen** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#25]
当前版本2.10.6(Build;200601) (Patch:1:5ad43a6)

作者现在还有在更新吗😂

**Comment by StarGolx** [comment]
貌似没了

**Comment by Kxnrl** [comment]
活了

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/releases/tag/2.2.1
