### ISSUE TITLE
网易云2.10.6最新版无法显示

### ISSUE THREAD

**Issue by dxz19** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#26]
我这边最新build是200601 看了一下貌似还是offset不对

**Comment by Kxnrl** [comment]
> 我这边最新build是200601 看了一下貌似还是offset不对

最新版为200791

**Comment by dxz19** [comment]
啊，这样吗，我这边检查了一下它说已经是最新版本了T T

**Comment by EagleZhen** [comment]
我这边200794又不行了☹️

**Comment by Kxnrl** [comment]
> 

你看看能不能提供cloudmusic.dll或者安装包

**Comment by Kxnrl** [comment]
> 我这边200794又不行了☹️

你看看能不能提供cloudmusic.dll或者安装包

**Comment by AlecS9** [comment]
大佬有打算支持2.10.7吗

**Comment by Kxnrl** [comment]
> 大佬有打算支持2.10.7吗

现在支持2.10.7.200791, 我没收到新的更新提示, 我手上也没有新版的dll. 所以我没法研究

**Comment by AlecS9** [comment]
> 

可惜了，我是200814
