### ISSUE TITLE
Request for new Netease Music version supports 2.10.10

### ISSUE THREAD

**Issue by Laurenfrost** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#29]
Could you please update offset for new Netease Music version `2.10.10`? Thank you very much!
And here is `cloudmusic.dll`.
[cloudmusic.zip](https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/files/11479760/cloudmusic.zip)

**Comment by Kxnrl** [comment]
Fixed in https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/commit/77db7673e021e6f97a2198cd28818034c93e42f9
