### ISSUE TITLE
V3.0.0 beta support

### ISSUE THREAD

**Issue by aliencaocao** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#32]
I have found the offsets here: https://github.com/aliencaocao/netease_cloudmusic_discord_rpc/blob/028ddf26778d57f7e1073c2325124fcb53f70fe9/src/main.py#L43

not a PR because this repo uses different offsets, so this is just a FYI to the author and other users.

For V3.0.0.beta build 201714

V3.0 switched to a multi-level pointer for the song array, current and length can still be found normally.

**Comment by Kxnrl** [comment]
3.0-alpha现已支持实时进度和暂停状态

https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/commit/455e53373f7c1dc8390b500883a805d10a974b69
