### ISSUE TITLE
动态没有显示

### ISSUE THREAD

**Issue by EW2266** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#5]
![image](https://user-images.githubusercontent.com/40555607/108635969-379d2180-7437-11eb-99dd-867532b46b06.png)

重启过后依旧没有显示

**Comment by Kxnrl** [comment]
offset 可能已经过期

**Comment by EW2266** [comment]
我看Issues里面最近没有其他人的post。
请问是我下载或者安装的时候做错了什么吗？
（我没有怎么写过java以外的东西， 如果这个问题是无关紧要的，那么请无视。。。)

**Comment by Kxnrl** [comment]
> 我看Issues里面最近没有其他人的post。
> 请问是我下载或者安装的时候做错了什么吗？
> （我没有怎么写过java以外的东西， 如果这个问题是无关紧要的，那么请无视。。。)

网易云的版本号是多少

**Comment by Kxnrl** [comment]
![image](https://user-images.githubusercontent.com/3905845/108641326-b9458b80-74d9-11eb-8d1d-be169dca772d.png)
 2.7.6 用最新版的应该可以了

**Comment by EW2266** [comment]
谢谢！
