### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by AssSlayer4** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#7]
it works like a few seconds then the rich presence stops suddenly
![image_2021-05-01_114522](https://user-images.githubusercontent.com/82951693/116790651-b6838b80-aa72-11eb-9cb7-d9fc4e0b0361.png)

**Comment by EagleZhen** [comment]
> it works like a few seconds then the rich presence stops suddenly
> ![image_2021-05-01_114522](https://user-images.githubusercontent.com/82951693/116790651-b6838b80-aa72-11eb-9cb7-d9fc4e0b0361.png)

I had the same problem.  I think it probably has something to do with the windows.txt file because every time I update the windows.txt file, the rich presence will reappear for a few seconds. After that, it will stop until I update the file next time.

**Comment by dxz19** [comment]
Happened to me as well, it only works for a few seconds when I start playing a new song manually and then stops working. It seems like the app is having trouble displaying the remaining time on the song. I really like this app and hopefully this issue can be resolved soon!

**Comment by Kxnrl** [comment]
offset out-of-date. please wait for next update.

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/releases/tag/2.0.2-final
