### ISSUE TITLE
动态显示异常

### ISSUE THREAD

**Issue by dxz19** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#8]
用的是最新版的网易云2.8.0，手动播放新歌时会更新动态但是歌曲进度显示00:00，然后过几秒动态就消失了，重启电脑后也是一样的情况。重新启动软件的话就没反应，discord动态也不会更新。

**Comment by Kxnrl** [comment]
网易2.8.0更新了4还是5个版本. 所以每个版本的offset都不一样, 所以2.8.0稍后会放出来当前我电脑上2.8.0的offset, 但是我也不能确定是不是最终版

**Comment by Kxnrl** [comment]
https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/releases/tag/2.0.2-final

**Comment by dxz19** [comment]
> https://github.com/Kxnrl/NetEase-Cloud-Music-DiscordRPC/releases/tag/2.0.2-final

非常感谢大佬！！最新版有在正常运行了:D
