### ISSUE TITLE
网易云2.9.1

### ISSUE THREAD

**Issue by EW2266** [Kxnrl/NetEase-Cloud-Music-DiscordRPC#9]
网易云版本2.9.1 没法显示剩余时间 并且会定格在程序开始时播放的歌无法切换
![image](https://user-images.githubusercontent.com/40555607/125535446-5b965a02-e417-4aba-aa7b-f7481e347008.png)

**Comment by Kxnrl** [comment]
你可以发送一个2.9.1的安装包给我吗, 我还没有收到这个版本的推送

**Comment by EW2266** [comment]
https://ucmerced.box.com/s/cyhtvvirr0ezju1u4br6t8t48iylm4at

**Comment by EW2266** [comment]
2.9.2 更新 build:199163 Patch: 1609925

**Comment by Kxnrl** [comment]
fixed in latest
